"""LLM judges, blind to condition. Returns AI-likelihood (0-100), fluency/coherence (1-5), relevance (1-5).
Backends (OpenRouter paid key was over its daily limit and the Cohere key is a 20 calls/min trial key, see REPORT):
  local      : meta-llama/Llama-3.1-8B-Instruct, greedy, on every generation
  cohere     : command-a-plus-05-2026 (Cohere API, trial key: ~20 calls/min, ~1000 calls total) on a stratified subset
  openrouter : nvidia/nemotron-3-super-120b-a12b:free (second, independent judge; free tier, reasoning effort low)
usage: python judge.py scores_xxx.parquet local|openrouter|cohere [cond_regex] [max_pid]"""
import sys, os, json, re, time, hashlib, threading
from concurrent.futures import ThreadPoolExecutor
import requests
import pandas as pd
from common import *

MODEL = "command-a-plus-05-2026"
TEMPLATE = """You are an expert in distinguishing human-written text from text produced by AI language models (chatbots such as ChatGPT, Claude, Qwen, Llama).

Below is a question and an answer to it. The answer may have been written by a human (e.g. an internet forum user or a domain expert) or generated by an AI model. It may be cut off at the end; ignore truncation.

QUESTION: {q}

ANSWER:
\"\"\"
{a}
\"\"\"

Rate the answer on three scales:
- ai_likelihood: 0-100, your probability (in percent) that this answer was written by an AI model rather than a human.
- fluency: 1-5, how fluent, grammatical and coherent the text is (5 = perfectly fluent and coherent, 1 = gibberish/degenerate repetition).
- relevance: 1-5, how well the answer addresses the question (5 = fully on-topic and responsive, 1 = unrelated).

Respond with only a JSON object: {{"ai_likelihood": <int>, "fluency": <int>, "relevance": <int>}}"""

lock = threading.Lock()


OR_MODEL = os.environ.get("OR_MODEL", "nvidia/nemotron-3-super-120b-a12b:free")


def parse(txt):
    j = json.loads(re.search(r"\{.*?\}", txt, re.S).group(0))
    return dict(ai_likelihood=float(j["ai_likelihood"]), fluency=float(j["fluency"]), relevance=float(j["relevance"]))


def call_openrouter(prompt, retries=8):
    import openai
    c = openai.OpenAI(api_key=os.environ["OPENROUTER_KEY"], base_url="https://openrouter.ai/api/v1")
    err = ""
    for k in range(retries):
        try:
            r = c.chat.completions.create(model=OR_MODEL, messages=[{"role": "user", "content": prompt}], temperature=0.0, max_tokens=2000,
                                           extra_body={"reasoning": {"effort": "low"}})
            return parse(r.choices[0].message.content)
        except Exception as e:
            err = str(e)[:300]; time.sleep(min(2 ** k, 60))
    return dict(error=err)


def judge_local(prompts, bs=48):
    from transformers import AutoModelForCausalLM, AutoTokenizer
    name = "meta-llama/Llama-3.1-8B-Instruct"
    tok = AutoTokenizer.from_pretrained(name); tok.pad_token = tok.eos_token; tok.padding_side = "left"
    m = AutoModelForCausalLM.from_pretrained(name, dtype=torch.bfloat16, device_map="cuda").eval()
    out = []
    for i in range(0, len(prompts), bs):
        t = [tok.apply_chat_template([{"role": "user", "content": p}], tokenize=False, add_generation_prompt=True) for p in prompts[i:i+bs]]
        enc = tok(t, return_tensors="pt", padding=True, add_special_tokens=False).to("cuda")
        with torch.no_grad():
            g = m.generate(**enc, max_new_tokens=40, do_sample=False, pad_token_id=tok.eos_token_id)
        for x in tok.batch_decode(g[:, enc.input_ids.shape[1]:], skip_special_tokens=True):
            try: out.append(parse(x))
            except Exception: out.append(dict(error=x[:200]))
    return out


def call(prompt, retries=20):
    err = ""
    for k in range(retries):
        try:
            r = requests.post("https://api.cohere.com/v2/chat", timeout=60,
                              headers={"Authorization": f"Bearer {os.environ['COHERE_API_KEY']}", "Content-Type": "application/json"},
                              json={"model": MODEL, "messages": [{"role": "user", "content": prompt}], "temperature": 0.0,
                                    "response_format": {"type": "json_object"}})
            if r.status_code == 429 or r.status_code >= 500:
                err = f"HTTP {r.status_code}: {r.text[:200]}"; time.sleep(min(5 * (k + 1), 60)); continue
            r.raise_for_status()
            txt = [c["text"] for c in r.json()["message"]["content"] if c.get("type") == "text"][0]
            j = json.loads(re.search(r"\{.*\}", txt, re.S).group(0))
            return dict(ai_likelihood=float(j["ai_likelihood"]), fluency=float(j["fluency"]), relevance=float(j["relevance"]))
        except Exception as e:
            err = str(e); time.sleep(2 ** min(k, 5))
    return dict(error=err)


if __name__ == "__main__":
    src, backend = sys.argv[1], sys.argv[2]
    df = pd.read_parquet(RES / src)
    if len(sys.argv) > 3: df = df[df.cond.str.match(sys.argv[3])]
    if len(sys.argv) > 4: df = df[df.pid < int(sys.argv[4])]
    prompts_by_file = {}
    for f in df.file.unique():
        prompts_by_file[f] = json.load(open(RES / ("pilot_prompts.json" if "pilot" in f else "steer_prompts.json")))
    out = RES / (f"judge_{backend}_" + Path(src).stem.replace("scores_", "") + ".jsonl")
    cache = {}
    if out.exists():
        for l in open(out):
            j = json.loads(l)
            if "error" not in j: cache[j["key"]] = j
    jobs = []
    for r in df.itertuples():
        q = prompts_by_file[r.file][r.pid]["q"]
        p = TEMPLATE.format(q=q, a=r.text[:3000])
        key = hashlib.md5(p.encode()).hexdigest()
        if key not in cache: jobs.append((key, r.file, r.cond, r.pid, p))
    print("to judge:", len(jobs), "cached:", len(cache))
    fh = open(out, "a")
    if backend == "local":
        res = judge_local([j[-1] for j in jobs])
        for (key, f, c, pid, _), r in zip(jobs, res):
            r.update(key=key, file=f, cond=c, pid=pid); fh.write(json.dumps(r) + "\n")
        fh.close(); sys.exit()

    def work(j):
        key, f, c, pid, p = j
        res = call(p) if backend == "cohere" else call_openrouter(p); res.update(key=key, file=f, cond=c, pid=pid)
        with lock:
            fh.write(json.dumps(res) + "\n"); fh.flush()
    with ThreadPoolExecutor(int(os.environ.get("JUDGE_WORKERS", 4))) as ex:
        list(ex.map(work, jobs))
    fh.close()
